<?php

/**
 * @file
 * Allows to add group content from entity form.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Entity\FieldableEntityInterface;

/**
 * Implements hook_theme().
 */
function entitygroupfield_theme()
{
  return [
    'entitygroupfield_dropbutton_wrapper' => [
      'variables' => ['children' => NULL],
    ],
  ];
}

/**
 * Implements hook_entity_base_field_info().
 */
function entitygroupfield_entity_base_field_info(EntityTypeInterface $entity_type)
{
  if ($entity_types = entitygroupfield_get_entity_types()) {
    // Adding field to entity types.
    if (array_key_exists($entity_type->id(), $entity_types)) {
      $field_label = $entity_type->id() === 'user' ? t('Group memberships') : t('Assigned permission groups');
      return [
        'entitygroupfield' => BaseFieldDefinition::create('entitygroupfield')
          ->setName('entitygroupfield')
          ->setTargetEntityTypeId($entity_type->id())
          ->setSetting('target_type', 'group_content')
          ->setLabel($field_label)
          ->setTranslatable(FALSE)
          ->setComputed(TRUE)
          ->setCustomStorage(TRUE)
          ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
          ->setClass('\Drupal\entitygroupfield\Field\EntityGroupFieldItemList')
          ->setDisplayConfigurable('form', TRUE)
          ->setDisplayOptions('form', [
            'region' => 'hidden',
            'weight' => 50,
          ])
          ->setDisplayConfigurable('view', TRUE)
          ->setDisplayOptions('view', [
            'label' => 'hidden',
            'region' => 'hidden',
            'weight' => 50,
          ])
      ];
    }
  }
  return [];
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function entitygroupfield_field_formatter_info_alter(array &$info)
{
  $info['entity_reference_entity_view']['field_types'][] = 'entitygroupfield';
}

/**
 * Get entities that should have a group content field.
 */
function entitygroupfield_get_entity_types()
{
  $entity_types = [];
  $plugin_manager = \Drupal::service('plugin.manager.group_content_enabler');
  foreach ($plugin_manager->getDefinitions() as $plugin_definition) {
    if ($entity_type_definition = \Drupal::entityTypeManager()->getDefinition($plugin_definition['entity_type_id'], FALSE)) {
      // Check if fields can be attached to the entity type.
      if ($entity_type_definition->entityClassImplements(FieldableEntityInterface::class)) {
        $entity_types[$plugin_definition['entity_type_id']]['label'] = (string) $entity_type_definition->getLabel();
        $entity_types[$plugin_definition['entity_type_id']]['bundles'][] = $plugin_definition['entity_bundle'];
      }
    }
  }
  return $entity_types;
}

/**
 * Returns the content enabler plugin IDs for a given entity type.
 *
 * @param string $entity_type_id
 *   The entity type ID.
 * @param string $bundle
 *   (optional) The entity bundle.
 *
 * @return string[]
 *   An array of group content enabler plugin IDs that match.
 */
function entitygroupfield_get_group_content_plugin_ids($entity_type_id, $bundle = NULL)
{
  $plugin_ids = [];
  foreach (\Drupal::service('plugin.manager.group_content_enabler')->getDefinitions() as $plugin_id => $plugin_info) {
    if ($plugin_info['entity_type_id'] === $entity_type_id) {
      if (isset($bundle) && !empty($plugin_info['entity_bundle']) && $plugin_info['entity_bundle'] !== $bundle) {
        continue;
      }
      $plugin_ids[] = $plugin_id;
    }
  }
  return $plugin_ids;
}
