field.formatter.settings.parent_group_entity_formatter:
  type: mapping
  label: 'Parent group entity formatter settings'
  mapping:
    view_mode:
      type: string
      label: 'View mode'

field.formatter.settings.parent_group_label_formatter:
  type: mapping
  label: 'Parent group label formatter settings'
  mapping:
    link:
      type: boolean
      label: 'Link to the entity'

field.widget.settings.entitygroupfield_autocomplete_widget:
  type: mapping
  label: 'Group autocomplete widget settings'
  mapping:
    help_text:
      type: text
      label: 'Help text'
    label:
      type: label
      label: 'Label'
    multiple:
      type: boolean
      label: 'Multiple'
    required:
      type: boolean
      label: 'Required'

field.widget.settings.entitygroupfield_select_widget:
  type: mapping
  label: 'Group select widget settings'
  mapping:
    help_text:
      type: text
      label: 'Help text'
    label:
      type: label
      label: 'Label'
    multiple:
      type: boolean
      label: 'Multiple'
    required:
      type: boolean
      label: 'Required'
